(function(){
  'use strict';
  var config=window.SB_SUPABASE,sessionKey='sb_admin_session',leads=[];
  var loginView=document.querySelector('[data-login-view]'),dashboard=document.querySelector('[data-dashboard]'),loginForm=document.querySelector('[data-login-form]'),loginMessage=document.querySelector('[data-login-message]'),dashboardMessage=document.querySelector('[data-dashboard-message]'),tbody=document.querySelector('[data-leads-body]'),empty=document.querySelector('[data-empty]'),search=document.querySelector('[data-search]'),filter=document.querySelector('[data-status-filter]');
  function message(element,text){element.textContent=text||'';}
  function getSession(){try{return JSON.parse(localStorage.getItem(sessionKey)||'null');}catch(error){return null;}}
  function setSession(value){if(value)localStorage.setItem(sessionKey,JSON.stringify(value));else localStorage.removeItem(sessionKey);}
  function showDashboard(show){loginView.hidden=show;dashboard.hidden=!show;}
  async function request(path,options){var session=getSession(),headers=Object.assign({apikey:config.key,Authorization:'Bearer '+(session?session.access_token:config.key)},options&&options.headers||{}),response=await fetch(config.url+path,Object.assign({},options||{},{headers:headers}));if(response.status===401&&session&&session.refresh_token){var refreshed=await refreshSession(session.refresh_token);if(refreshed)return request(path,options);}if(!response.ok){var details=await response.json().catch(function(){return{};});throw new Error(details.message||details.hint||details.error_description||'Request failed');}if(response.status===204||response.headers.get('content-length')==='0')return null;return response.json();}
  async function refreshSession(token){var response=await fetch(config.url+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:config.key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:token})});if(!response.ok){setSession(null);showDashboard(false);return null;}var session=await response.json();setSession(session);return session;}
  async function loadLeads(){message(dashboardMessage,'Loading leads…');try{leads=await request('/rest/v1/butcher_leads?select=*&order=created_at.desc');render();message(dashboardMessage,'');document.querySelector('[data-last-update]').textContent='Updated '+new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date());}catch(error){message(dashboardMessage,error.message.indexOf('butcher_leads')>-1?'Database setup required. Run supabase/schema.sql in the Supabase SQL Editor.':error.message);}}
  function escapeHtml(value){return String(value==null?'':value).replace(/[&<>'"]/g,function(char){return{'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char];});}
  function safeUrl(value){try{var url=new URL(value);return url.protocol==='http:'||url.protocol==='https:'?url.href:'';}catch(error){return '';}}
  function render(){var term=search.value.trim().toLowerCase(),status=filter.value,filtered=leads.filter(function(lead){var searchable=[lead.full_name,lead.butcher_shop,lead.email,lead.phone,lead.city_country].join(' ').toLowerCase();return(!term||searchable.indexOf(term)>-1)&&(!status||lead.status===status);});tbody.innerHTML=filtered.map(function(lead){var cleanWebsite=safeUrl(lead.website),website=cleanWebsite?'<a class="website-link" href="'+escapeHtml(cleanWebsite)+'" target="_blank" rel="noopener">Open site ↗</a>':'—';return'<tr><td>'+escapeHtml(new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(lead.created_at)))+'</td><td class="contact"><strong>'+escapeHtml(lead.full_name)+'</strong><a href="mailto:'+escapeHtml(lead.email)+'">'+escapeHtml(lead.email)+'</a><a href="tel:'+escapeHtml(lead.phone)+'">'+escapeHtml(lead.phone)+'</a></td><td class="shop"><strong>'+escapeHtml(lead.butcher_shop)+'</strong><span>'+escapeHtml(lead.has_website||'')+'</span></td><td>'+escapeHtml(lead.city_country)+'</td><td>'+website+'</td><td><span class="lang">'+escapeHtml(lead.language)+'</span></td><td><select class="status-select" data-lead-status="'+escapeHtml(lead.id)+'"><option value="new">New</option><option value="contacted">Contacted</option><option value="qualified">Qualified</option><option value="customer">Customer</option><option value="closed">Closed</option></select></td></tr>';}).join('');filtered.forEach(function(lead,index){tbody.querySelectorAll('[data-lead-status]')[index].value=lead.status||'new';});empty.hidden=filtered.length!==0;document.querySelector('[data-stat-total]').textContent=leads.length;document.querySelector('[data-stat-new]').textContent=leads.filter(function(x){return x.status==='new';}).length;document.querySelector('[data-stat-contacted]').textContent=leads.filter(function(x){return x.status==='contacted';}).length;document.querySelector('[data-stat-customer]').textContent=leads.filter(function(x){return x.status==='customer';}).length;}
  async function updateStatus(id,status,select){select.disabled=true;try{await request('/rest/v1/butcher_leads?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({status:status})});var lead=leads.find(function(item){return item.id===id;});if(lead)lead.status=status;render();}catch(error){message(dashboardMessage,error.message);}finally{select.disabled=false;}}
  function exportCsv(){var fields=['created_at','full_name','butcher_shop','phone','email','city_country','website','has_website','language','status','source_page'],rows=[fields].concat(leads.map(function(lead){return fields.map(function(field){return lead[field]||'';});})),csv=rows.map(function(row){return row.map(function(value){return '"'+String(value).replace(/"/g,'""')+'"';}).join(',');}).join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='sb-marketing-leads-'+new Date().toISOString().slice(0,10)+'.csv';link.click();URL.revokeObjectURL(link.href);}
  loginForm.addEventListener('submit',async function(event){event.preventDefault();var button=loginForm.querySelector('button'),data=new FormData(loginForm),email=String(data.get('email')).trim().toLowerCase();message(loginMessage,'');if(email!==config.adminEmail){message(loginMessage,'This account is not authorised.');return;}button.disabled=true;button.textContent='Signing in…';try{var response=await fetch(config.url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:config.key,'Content-Type':'application/json'},body:JSON.stringify({email:email,password:data.get('password')})}),session=await response.json();if(!response.ok)throw new Error(session.error_description||session.msg||'Unable to sign in');setSession(session);showDashboard(true);loadLeads();}catch(error){message(loginMessage,error.message);}finally{button.disabled=false;button.textContent='Sign in';}});
  tbody.addEventListener('change',function(event){var select=event.target.closest('[data-lead-status]');if(select)updateStatus(select.dataset.leadStatus,select.value,select);});search.addEventListener('input',render);filter.addEventListener('change',render);document.querySelector('[data-refresh]').addEventListener('click',loadLeads);document.querySelector('[data-export]').addEventListener('click',exportCsv);document.querySelector('[data-logout]').addEventListener('click',function(){setSession(null);leads=[];showDashboard(false);loginForm.reset();});
  if(!config){message(loginMessage,'Supabase configuration is missing.');return;}var session=getSession();if(session&&session.expires_at*1000>Date.now()){showDashboard(true);loadLeads();}else if(session&&session.refresh_token){refreshSession(session.refresh_token).then(function(value){if(value){showDashboard(true);loadLeads();}});}else showDashboard(false);
})();
